// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoExamenU2.Databases.LogsDataBase;

#nullable disable

namespace ProyectoExamenU2.Migrations.LogsDatabase
{
    [DbContext(typeof(LogsContext))]
    [Migration("20241115155447_INITLogsDatabase")]
    partial class INITLogsDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoExamenU2.Databases.LogsDataBase.Entities.LogDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ChangeType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("change_type");

                    b.Property<Guid?>("EntityRowId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("row_id");

                    b.Property<string>("EntityTableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tableAfected");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_values");

                    b.HasKey("Id");

                    b.ToTable("LogsDetails");
                });

            modelBuilder.Entity("ProyectoExamenU2.Databases.LogsDataBase.Entities.LogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("DetailId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("log_detail_id");

                    b.Property<Guid?>("ErrorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("log_error_id");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DetailId");

                    b.HasIndex("ErrorId");

                    b.ToTable("logs", "dbo");
                });

            modelBuilder.Entity("ProyectoExamenU2.Databases.LogsDataBase.Entities.LogErrorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stack_trace");

                    b.Property<string>("TargetSite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target_site");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("time_stamp");

                    b.HasKey("Id");

                    b.ToTable("LogsErrors");
                });

            modelBuilder.Entity("ProyectoExamenU2.Databases.LogsDataBase.Entities.LogEntity", b =>
                {
                    b.HasOne("ProyectoExamenU2.Databases.LogsDataBase.Entities.LogDetailEntity", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoExamenU2.Databases.LogsDataBase.Entities.LogErrorEntity", "Error")
                        .WithMany()
                        .HasForeignKey("ErrorId");

                    b.Navigation("Detail");

                    b.Navigation("Error");
                });
#pragma warning restore 612, 618
        }
    }
}
